apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prom
spec:
  replicas: 1
  template:
    metadata:
      name: prom
      labels:
        app: prom
    spec:
      containers:
      - name: ci-fetcher
        image: registry.fedoraproject.org/fedora:30
        command:
        - /bin/bash
        - -c
        - |
          #!/bin/bash
          set -exuo pipefail
          curl -sL ${PROMTAR} | tar --no-overwrite-dir xvz
          pkill -HUP /bin/prometheus
        env:
          - name: PROMTAR
            value: "PROMTAR_VALUE"
        workingDir: /prometheus/
        volumeMounts:
        - name: prometheus-storage-volume
          mountPath: /prometheus/
      - name: prometheus
        image: prom/prometheus:v2.12.0
        ports:
        - name: webui
          containerPort: 9090
        resources:
          requests:
            cpu: 500m
            memory: 500M
          limits:
            cpu: 500m
            memory: 500M
        volumeMounts:
        - name: prometheus-storage-volume
          mountPath: /prometheus/
      shareProcessNamespace: true
      volumes:
        - name: prometheus-storage-volume
          emptyDir: {}
