apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prom
  namespace: prom-test
spec:
  replicas: 1
  template:
    metadata:
      name: prom
      labels:
        app: prom
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.12.0
        ports:
        - name: webui
          containerPort: 9090
        resources:
          requests:
            cpu: 500m
            memory: 500M
          limits:
            cpu: 500m
            memory: 500M
        volumeMounts:
        - name: prometheus-storage-volume
          mountPath: /prometheus/
      volumes:
        - name: prometheus-storage-volume
          emptyDir: {}
