apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prom
spec:
  replicas: 1
  template:
    metadata:
      name: prom
      labels:
        app: prom
    spec:
      initContainers:
      - name: ci-fetcher
        image: registry.fedoraproject.org/fedora:30
        command:
        - /bin/bash
        - -c
        - |
          curl -sL ${PROMTAR} | tar xvz --no-overwrite-dir || true
        env:
          - name: PROMTAR
            value: "PROMTAR_VALUE"
        workingDir: /data/
        volumeMounts:
        - name: prometheus-storage-volume
          mountPath: /data/
      containers:
      - name: prometheus
        image: prom/prometheus:v2.12.0
        ports:
        - name: webui
          containerPort: 9090
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 500m
            memory: 2Gi
        volumeMounts:
        - name: prometheus-storage-volume
          mountPath: /data/
      shareProcessNamespace: true
      volumes:
        - name: prometheus-storage-volume
          emptyDir: {}
