apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prom
spec:
  replicas: 1
  template:
    metadata:
      name: prom
      labels:
        app: prom
    spec:
      containers:
      - name: ci-fetcher
        image: registry.fedoraproject.org/fedora:30
        command:
        - /bin/bash
        - -c
        - |
          #!/bin/bash
          set -exuo pipefail
          {
            echo "global:"
            echo "  evaluation_interval: 30s"
            echo "  scrape_interval: 30s"
          } > prometheus.yml
          curl -sL ${PROMTAR} | tar xvz --no-overwrite-dir || true
          kill -HUP $(fgrep "prometheus" /proc/*/comm -l | cut -d '/' -f 3)
          sleep infinity
        env:
          - name: PROMTAR
            value: "PROMTAR_VALUE"
        workingDir: /data/
        volumeMounts:
        - name: prometheus-storage-volume
          mountPath: /data/
      - name: prometheus
        image: prom/prometheus:v2.12.0
        args:
          - --storage.tsdb.path=/prometheus
          - --config.file=/prometheus/prometheus.yml
        ports:
        - name: webui
          containerPort: 9090
        resources:
          requests:
            cpu: 500m
            memory: 500M
          limits:
            cpu: 500m
            memory: 500M
        volumeMounts:
        - name: prometheus-storage-volume
          mountPath: /data/
      shareProcessNamespace: true
      volumes:
        - name: prometheus-storage-volume
          emptyDir: {}
