apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prom
spec:
  replicas: 1
  template:
    metadata:
      name: prom
      labels:
        app: prom
    spec:
      initContainers:
      - name: ci-fetcher
        image: registry.fedoraproject.org/fedora:30
        command:
        - /bin/bash
        - -c
        - |
          set -uxo pipefail
          umask 0000
          curl -sL ${PROMTAR} | tar xvz -m
        workingDir: /prometheus/
        envFrom:
          - configMapRef:
              name: promtar
        volumeMounts:
        - name: prometheus-storage-volume
          mountPath: /prometheus/
      containers:
      - name: prometheus
        image: prom/prometheus:v2.12.0
        ports:
        - name: webui
          containerPort: 9090
        readinessProbe:
          httpGet:
            path: /
            port: 9090
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
        volumeMounts:
        - name: prometheus-storage-volume
          mountPath: /prometheus/
      shareProcessNamespace: true
      volumes:
        - name: prometheus-storage-volume
          emptyDir: {}
