commonLabelsAndSelectors:
  app: COMMON_LABEL
namePrefix: COMMON_LABEL-
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: prom
  spec:
    template:
      spec:
        containers:
        - name: ci-fetcher
          env:
            - name: PROMTAR
              value: "PROMTAR_VALUE"
