apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: promecieus
  namespace: promecieus
  labels:
    app: promecieus
spec:
  lookupPolicy:
    local: false
  tags:
  - name: latest
    referencePolicy:
      type: Source
