kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: promecieus-robot-cluster-admin
subjects:
  - kind: ServiceAccount
    name: promecieus-robot
    namespace: promecieus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
