namespace: pod-hunt
resources:
  - 01-namespace.yaml
  - 02-imagestream.yaml
  - 03-buildconfig-src.yaml
  - 04-buildconfig-bin.yaml
  - 05-deploymentconfig.yaml
  - 06-service.yaml
  - 07-route.yaml
  - 08-serviceaccount.yaml
  - 09-clusterrolebinding.yaml
vars:
  - name: SITE_HOSTNAME
    objref:
      kind: Route
      name: promecieus
      apiVersion: route.openshift.io/v1
    fieldref:
      fieldpath: spec.host
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: promecieus-config
    literal:
      - ROUTE=$(SITE_HOSTNAME)
